# Generated by Django 5.2.5 on 2025-11-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_hdfctransactiondetails_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdfctransactiondetails',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
